name: Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      # Generate token for GitHub App
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Checkout with the app token
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Update verifier dependency
        run: |
          # Use your app's bot user - replace APP_SLUG with your app's slug
          git config --local user.email "YOUR_APP_ID+YOUR_APP_SLUG[bot]@users.noreply.github.com"
          git config --local user.name "YOUR_APP_SLUG[bot]"
          go get -u github.com/tinfoilsh/verifier
          git add .
          git commit -m "chore: bump verifier"
          git push origin main

      - name: Set up xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up gomobile
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/mobile/cmd/gomobile
          go get -u golang.org/x/mobile/cmd/gobind
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile init -v

      - name: Build XCFramework
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          gomobile bind -v -target=ios,macos -o Tinfoil.xcframework $(go list ./... | grep -v "/examples/" | xargs)
          zip -r Tinfoil.xcframework.zip Tinfoil.xcframework

      - name: Generate checksum
        run: shasum -a 256 Tinfoil.xcframework.zip > Tinfoil.xcframework.zip.sha256

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Tinfoil.xcframework.zip
            Tinfoil.xcframework.zip.sha256
          generate_release_notes: true
          fail_on_unmatched_files: true
