name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Set up xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run tests
        run: go test -v ./...

      - name: Set up gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile init

      - name: Build XCFramework
        run: |
          echo "Building XCFramework for version ${GITHUB_REF#refs/tags/}"
          gomobile bind -target=ios -o Tinfoil.xcframework $(go list ./...)

      - name: Create ZIP archive
        run: |
          zip -r Tinfoil.xcframework.zip Tinfoil.xcframework
          echo "Created archive for version ${GITHUB_REF#refs/tags/}"
          ls -lh Tinfoil.xcframework.zip

      - name: Generate checksum
        run: shasum -a 256 Tinfoil.xcframework.zip > Tinfoil.xcframework.zip.sha256

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Tinfoil.xcframework.zip
            Tinfoil.xcframework.zip.sha256
          generate_release_notes: true
          fail_on_unmatched_files: true
