name: SDK Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod

      - name: Set up xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: latest-stable

      - name: Set up gomobile
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/mobile/cmd/gomobile
          go get -u golang.org/x/mobile/cmd/gobind
          go install golang.org/x/mobile/cmd/gomobile
          go install golang.org/x/mobile/cmd/gobind
          gomobile init -v

      - name: Build XCFramework
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          gomobile bind -v -target=ios,iossimulator,macos -o Tinfoil.xcframework $(go list ./... | grep -v -E "/examples/|/rootfetch" | xargs)
          zip -ry Tinfoil.xcframework.zip Tinfoil.xcframework

      - name: Generate checksum
        run: shasum -a 256 Tinfoil.xcframework.zip > Tinfoil.xcframework.zip.sha256

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: |
            Tinfoil.xcframework.zip
            Tinfoil.xcframework.zip.sha256
          generate_release_notes: true
          fail_on_unmatched_files: true
